### ISSUE TITLE
Comments and blank lines are not counted as lines

### ISSUE THREAD

**Issue by atombender** [kaaveland/eugene#104]
Consider a script like this:

```shell
$ cat <<end | eugene lint -
ALTER TABLE foo ADD a text;


-- A comment
CREATE UNIQUE INDEX my_index ON foo (a);
end
```

Produces:

```
stdin:1 E9 Taking dangerous lock without timeout https://kaveland.no/eugene/hints/E9/
stdin:1 E4 Running more statements after taking `AccessExclusiveLock` https://kaveland.no/eugene/hints/E4/
stdin:1 E6 Creating a new index on an existing table https://kaveland.no/eugene/hints/E6/
stdin:1 E9 Taking dangerous lock without timeout https://kaveland.no/eugene/hints/E9/
```

I expected:

```
stdin:1 E9 Taking dangerous lock without timeout https://kaveland.no/eugene/hints/E9/
stdin:1 E4 Running more statements after taking `AccessExclusiveLock` https://kaveland.no/eugene/hints/E4/
stdin:5 E6 Creating a new index on an existing table https://kaveland.no/eugene/hints/E6/
stdin:5 E9 Taking dangerous lock without timeout https://kaveland.no/eugene/hints/E9/
```

The same behaviour is seen if with a file, so it is unrelated to the use of stdin.

Some testing seems to indicate that the code counts lines in a very strange way. For example, this also miscounts, and reports the index problem on line 4 (it's line 6):

```
ALTER TABLE
    foo
ADD
    a text;

CREATE UNIQUE INDEX
    my_index ON foo (a);
```

**Comment by kaaveland** [comment]
Thanks, this is a very useful report. Are you using the latest version? I know that this part of the code needs some work, I'll try to get around to it next week or so (in the process of moving to a new house now). Edit: Definitely a problem in 0.6.1.

**Comment by atombender** [comment]
Yep!

```shell
$ eugene --version
eugene 0.6.1

```

**Comment by kaaveland** [comment]
Release for 0.6.2 which fixes this, is in progress and should be up soon.

**Comment by atombender** [comment]
Thanks for the super quick response. I can confirm that it fixes my issue.
